# Generated by Django 3.2.8 on 2022-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='operation_type',
            field=models.CharField(choices=[('addition', 'addition'), ('subtraction', 'subtraction'), ('multiplication', 'multiplication')], max_length=255),
        ),
    ]
