# Generated by Django 3.2.8 on 2022-11-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuri', '0002_alter_operations_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='slackUsername',
            field=models.CharField(default='Lash', max_length=20),
        ),
    ]
